/* Catálogo único — Ofertas De Mulher (panela, jaqueta, toalha) */
window.TTK_CATALOG = {
  brand: "Ofertas De Mulher",
  logo: "/images/logo-loja.png",
  soldLabel: "168,1 mil vendido(s)",
  followers: "42,6 mil seguidores",
  stats: { reply: "90%", ship: "94%" },
  about:
    "Loja oficial com ofertas em moda, casa e utilidades. Envio rápido, atendimento em português e pagamento seguro via Pix.",
  products: [
    {
      id: "panelas",
      title: "Jogo de Panelas Cerâmica Antiaderente 13 Peças",
      url: "/panela/",
      image: "/images/01.png",
      priceLabel: "A partir de R$ 69,90",
      priceMain: "69,90",
      badge: "-62%",
      sold: "28,4 mil vendidos",
      rating: "4.8",
    },
    {
      id: "jaqueta",
      title: "Jaqueta Feminina Puffer Forrada Premium",
      url: "/jaqueta/",
      image: "/jaqueta/images/01.png",
      priceLabel: "A partir de R$ 34,99",
      priceMain: "34,99",
      badge: "-68%",
      sold: "51,2 mil vendidos",
      rating: "4.9",
    },
    {
      id: "conjunto",
      title: "Conjunto Feminino Alfaiataria Blusa Blazer e Calça Pantalona",
      url: "/conjunto/",
      image: "/conjunto/images/01.png",
      priceLabel: "A partir de R$ 44,12",
      priceMain: "44,12",
      badge: "-55%",
      sold: "9,8 mil vendidos",
      rating: "4.9",
    },
    {
      id: "roupao",
      title: "Roupão Microfibra Plush Adulto Unissex",
      url: "/roupao/",
      image: "/roupao/images/hero-01.png",
      priceLabel: "A partir de R$ 34,91",
      priceMain: "34,91",
      badge: "-60%",
      sold: "4,1 mil vendidos",
      rating: "4.9",
    },
    {
      id: "teddy",
      title: "Casaquinho Teddy Feminino Sherpa Inverno",
      url: "/teddy/",
      image: "/teddy/images/hero-04.png",
      priceLabel: "A partir de R$ 28,17",
      priceMain: "28,17",
      badge: "-68%",
      sold: "8,2 mil vendidos",
      rating: "4.8",
    },
    {
      id: "bobojaco",
      title: "Jaqueta Feminina Cotêle Grosso Bobojaco",
      url: "/bobojaco/",
      image: "/bobojaco/images/hero-02.png",
      priceLabel: "A partir de R$ 36,59",
      priceMain: "36,59",
      badge: "-68%",
      sold: "12,4 mil vendidos",
      rating: "4.8",
    },
    {
      id: "toalha",
      title: "Kit 4 Toalhas de Banho Gigante 100% Algodão",
      url: "/toalha/",
      image: "/toalha/imagens/01.png",
      priceLabel: "A partir de R$ 34,99",
      priceMain: "34,99",
      badge: "-68%",
      sold: "19,7 mil vendidos",
      rating: "4.9",
    },
    {
      id: "sabonete",
      title: "Kit Sabonete Granado — 8 ou 16 unidades 90g",
      url: "/sabonete/",
      image: "/sabonete/images/01.png",
      priceLabel: "A partir de R$ 26,96",
      priceMain: "26,96",
      badge: "-64%",
      sold: "3,2 mil vendidos",
      rating: "4.6",
    },
  ],
};
